[package]
name = "registry"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
shared.workspace = true
infra.workspace = true
application.workspace = true

anyhow.workspace = true
mockall.workspace = true
